### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by johncadengo** [ehfd/docker-nvidia-glx-desktop#14]
I'm trying to convert your example of using a docker run command `docker run --gpus 1 -it -e TZ=UTC -e SIZEW=1920 -e SIZEH=1080 -e SHARED=TRUE -e PASSWD=mypasswd -e VIDEO_PORT=DFP -p 8080:8080 ehfd/nvidia-glx-desktop:latest` into a docker compose file.

Here is my file:

```
version: '3.8'
services:
  nvidia-glx-desktop:
    image: 'ehfd/nvidia-glx-desktop:latest'
    environment:
      - TZ=UTC
      - SIZEW=1920
      - SIZEH=1080
      - SHARED=TRUE
      - PASSWD=mypasswd
      - VIDEO_PORT=DFP
    ports:
      - '8080:8080'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]
```

When I run it with your command, `xrandr` returns the correct value, mimicking a screen. However, when I run it with docker compose, `xrandr` is a virtual screen, at something like 32000 x 32000 screen size. Is there some subtle difference I'm not understanding?

**Comment by ehfd** [comment]
Please upload the /tmp/bootstrap--stdout.log and /var/log/Xorg.0.log files.

**Comment by johncadengo** [comment]
/tmp/bootstrap--stdout.log 
https://pastebin.com/irk8Y

/var/log/Xorg.0.log
https://pastebin.com/AFhWZzgQ

**Comment by johncadengo** [comment]
By the way, I have 2 GPUs on this system. So I am just sharing one with the docker container in testing.

**Comment by ehfd** [comment]
While the bootstrap-stdout.log is an invalid link and thus I cannot deduce the whole issue, try using DP-0 for VIDEO_PORT. I see that it is a Quadro GPU.

**Comment by johncadengo** [comment]
My apologies, a few characters were cut off in the copy and paste. Here's the link (and updated the original comment): https://pastebin.com/irk8YWBA

**Comment by johncadengo** [comment]
Changing the environment variable to `VIDEO_PORT=DP-0` did not work. Maybe the bootstrap log will help.

**Comment by ehfd** [comment]
```
version: '3.8'
services:
  glx:
    image: 'ghcr.io/ehfd/nvidia-glx-desktop:latest'
    environment:
      - TZ=UTC
      - SIZEW=1920
      - SIZEH=1080
      - SHARED=TRUE
      - PASSWD=mypasswd
      - VIDEO_PORT=DFP
    ports:
      - '8080:8080'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility]
    stdin_open: true
    tty: true
```

I had no issues at all with this configuration. Try using the latest [docker-compose version](https://docs.docker.com/compose/install/) rather than the one installed with the package manager..
